api_host: to-colo-pve05
api_password: a10networks
api_user: root@pam
args_414:
- data_ip: 10.10.0.1
  manage_ip: 10.12.1.151
  port: 12341
  vmid: 1109
args_502:
- data_ip: 10.10.0.2
  manage_ip: 10.12.1.152
  port: 12342
  vmid: 1110
- data_ip: 10.10.0.3
  manage_ip: 10.12.1.153
  port: 12343
  vmid: 1111
ctbridge: vmbr0
ctbridge10: vmbr10
ctbridge20: vmbr20
ctbridge30: vmbr30
ctcores: 2
ctdisk: 10
ctgw: 10.12.1.1
cthostname: server.puppet.com
ctmemory: 1024
ctnameserver: 8.8.8.8
ctnum: 2
ctpassword: password
ctstorage: local-lvm
ctswap: 512
node: to-colo-pve05
num_414: 1
num_502: 2
os_template: puppet.tar.gz
pubkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDtbRVX5ENRF9+AimevwtRjSJlTXhNZDZ5V7F3Z2RPDnGnxDs9G2PUaxMBYa2EU3ZF68SiL1fjUuLS6sZOb2o9i9d/WqyOQRlEQ+l05LDrzpZzgWiJ4em5+sBILHtX0n1YOoLI3njmM6knQqooMTWM22vsFg88GhQmaBbkiK3MRe/yV7AGXVa96h+2lflSMY2g1+7Z/eqjuLOzeTAXxGil+hxo49SPmi77jia4vQMYRupp32U8HTGfA3o2/GTsRel0murEJTf1y6ZduC1WsAp0aDWaVsNfN1PurizS751P7t4SqYM6IOjLYHV1G5NwS0qlO00MLwSLWZ8vZVQxN2Btqt5kAr5CkAO9sQOz2wrmSlMtzQQXsAOmlvH2TZ8NKjWPa05ikUmLmJIaq+7jP9fMb/ts5StaBTke+YMVBaA+Z/MsTtd68D6XFf1ePk9M1lNmu67HOT5a5xEoW8mNKZIeXubhGN6dmRPdgXstjrMKeZhrjRH8ufMBBI9OWL8P6hWE=
  root@arch
searchdomain: puppet.com
testbedargs:
  AX1: 10.12.1.152
  AX1_TERM_PORT: '12341'
  AX2: 10.12.1.153
  AX2_TERM_PORT: '12342'
  CLI1: 10.12.1.154
  MGMT: 10.12.1.157
  MGMT_GW_IP: 10.12.1.1
  RTR1: 10.12.1.151
  RTR1_TERM_PORT: '12343'
  SRV1: 10.12.1.155
  TERM_SRV: 10.12.1.105
ubuntus:
- hostname: puppet-server
  ip: 10.12.1.154
  nic:
  - eno1
  - eno2
  - eno3
  - eno4
  vlan_ip:
  - 10.10.0.4
  - 20.20.0.4
  - 30.30.0.4
  vmid: 1107
- hostname: puppet-client
  ip: 10.12.1.155
  nic:
  - eno1
  - eno2
  - eno3
  - eno4
  vlan_ip:
  - 10.10.0.5
  - 20.20.0.5
  - 30.30.0.5
  vmid: 1108
vmbridge: vmbr0
vmbridge10: vmbr10
vmbridge20: vmbr20
vmbridge30: vmbr30
vmcores: 2
vmdisk: 15
vmids:
- 1109
- 1110
- 1111
vmmemory: 4096
vmname: vThunder
vmvcpus: 1
