---
# Varialble for All

# --- Informasi Proxmox --- #
node        : to-colo-pve05
api_user    : root@pam
api_password: a10networks
api_host    : to-colo-pve05


# --- Setting Container --- #
OS_Template : puppet.tar.gz
# ubuntu-20.04-standard_20.04-1_amd64.tar.gz
# ubuntu-16.04-standard_16.04-1_amd64.tar.gz 
# centos-7-default_20171212_amd64.tar.xz

# ctid        : 1003
cthostname  : server.puppet.com
ctpassword  : password
searchdomain: puppet.com
ctnameserver: 8.8.8.8
ctcores     : 2
ctmemory    : 1024
ctswap      : 512
ctdisk      : 10
ctstorage   : local-lvm

# ctip        : 10.12.1.201/24
ctgw        : 10.12.1.1
ctbridge    : vmbr0
ctbridge10  : vmbr10
ctbridge20  : vmbr20
ctbridge30  : vmbr30

# --- Setting Virtual Machine --- #
vmname      : vThunder
vmcores     : 2
vmvcpus     : 1
vmmemory    : 4096
vmdisk      : 15
vmbridge    : vmbr0
vmbridge10  : vmbr10
vmbridge20  : vmbr20
vmbridge30  : vmbr30

ubuntus     :
  - { vmid: '1004', hostname: 'puppet-server', ip: '10.12.1.202', nic: ["eno1","eno2","eno3","eno4"], vlan_ip: ["10.10.0.4","20.20.0.4","30.30.0.4"] }
  - { vmid: '1005', hostname: 'puppet-client', ip: '10.12.1.206', nic: ["eno1","eno2","eno3","eno4"], vlan_ip: ["10.10.0.5","20.20.0.5","30.30.0.5"] }
pubkey      : ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDtbRVX5ENRF9+AimevwtRjSJlTXhNZDZ5V7F3Z2RPDnGnxDs9G2PUaxMBYa2EU3ZF68SiL1fjUuLS6sZOb2o9i9d/WqyOQRlEQ+l05LDrzpZzgWiJ4em5+sBILHtX0n1YOoLI3njmM6knQqooMTWM22vsFg88GhQmaBbkiK3MRe/yV7AGXVa96h+2lflSMY2g1+7Z/eqjuLOzeTAXxGil+hxo49SPmi77jia4vQMYRupp32U8HTGfA3o2/GTsRel0murEJTf1y6ZduC1WsAp0aDWaVsNfN1PurizS751P7t4SqYM6IOjLYHV1G5NwS0qlO00MLwSLWZ8vZVQxN2Btqt5kAr5CkAO9sQOz2wrmSlMtzQQXsAOmlvH2TZ8NKjWPa05ikUmLmJIaq+7jP9fMb/ts5StaBTke+YMVBaA+Z/MsTtd68D6XFf1ePk9M1lNmu67HOT5a5xEoW8mNKZIeXubhGN6dmRPdgXstjrMKeZhrjRH8ufMBBI9OWL8P6hWE= root@arch