- hosts: central
  tasks:
  - name: copy testbed file
    copy:
      src: "AXSoftVM1001TBCfg.tcl"
      dest: "/home/automation/TESTBEDS/"
      mode: 777
      owner: automation
      group: automation

- hosts: central
  tasks:
  - name: chmod
    shell: "chmod 755 /home/automation/TESTBEDS/AXSoftVM1001TBCfg.tcl"
    register: myoutput
    changed_when: myoutput.rc != 0
      
- hosts: proxmox
  gather_facts: no
  #connection: local
  roles:
      - container
      - vm

- hosts: ubuntu
  # connection: local
  gather_facts: no
  roles:
    - ubuntu

#- hosts: vthunder
#  connection: local 
#  gather_facts: no
#  roles:
#    - a10
