---

- hosts: central
  tasks:
  - name: copy testbed file
    copy:
      src: "AXSoftVM1001TBCfg.tcl"
      dest: "/home/automation/TESTBEDS/"
      mode: 755
      owner: automation
      group: automation

      
# - hosts: proxmox
#   gather_facts: no
#   connection: local
#   roles:
#       - container
#       - vm
#       - set

# - hosts: ubuntu
#   # connection: local
#   gather_facts: no
#   roles:
#     - ubuntu

#- hosts: vthunder
#  connection: local 
#  gather_facts: no
#  roles:
#    - a10
