---

- hosts: proxmox
  gather_facts: no
  roles:
      - container
        #- vm


        #- hosts: vthunder
        #  connection: local 
        #  gather_facts: no
        #  roles:
        #    - a10
