---

- hosts: proxmox
  gather_facts: no
  roles:
      # - container
      # - vm
      - set

# - hosts: ubuntu
#   # connection: local
#   gather_facts: no
#   roles:
#     - ubuntu

#- hosts: vthunder
#  connection: local 
#  gather_facts: no
#  roles:
#    - a10
