# This file is for testing
- hosts: ubuntu
  # connection: local
  gather_facts: no
  roles:
    - ubuntu
# - name: ping test
#   hosts: proxmox
#   gather_facts: false
#   connection: local
#   tasks:
#   - name: "telnet a10"
#     ansible.netcommon.telnet:
#       # host: 10.12.1.105
#       user: "admin"
#       password: "a10"
#       port: "12341"
#       login_prompt: "vThunder login: "
#       password_prompt: "Password:"
#       # enablepassword: "\n"
#       prompts:
#         - 'vThunder(NOLICENSE)>'
#       command:
#         - en
#     register: ping

#   - name: output
#     debug: "msg={{ ping.output }}"
