---
- name: >
    "Clone VM with only source VM name.
    The VM source is spynal.
    The target VM name is puppet"
  community.general.proxmox_kvm:
    # vmid: "{{ item }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    clone: clone1
    name: "puppet{{ item }}"
    node: "{{ node }}"
    storage: local-lvm
    format: qcow2
    timeout: 2000

- name: Start VM
  proxmox_kvm:
    node: "{{ node }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    name: "puppet{{ item }}"
    state: "started"
    update: true
