- name: create start vm
  block:
    - name: CREATE VM414
      include_tasks: create_vm414.yml
      loop: "{{ range(1000, 1001, 1)|list }}"
    - name: CREATE VM502
      include_tasks: create_vm502.yml
      loop: "{{ range(1001, 1003, 1)|list }}"
    - name: Wait for prepare
      pause:
        seconds: 30
    - name: START VMS
      include_tasks: start.yml
      loop: "{{ range(1000, 1003, 1)|list }}"
