- name: create start ct
  block:
    - name: CREATE PUPPET
      include_tasks: create_start_ct.yml
      loop: "{{ ubuntus }}"
- name: Wait 40s for prepare
  pause:
    seconds: 40
- name: Start CT
  block:
    - name: START PUPPET
      include_tasks: start_ct.yml
      loop: "{{ ubuntus }}"
