- name: create start ct
  block:
    - name: CREATE PUPPET
      include_tasks: create_start_ct.yml
      loop: 
        - { vmid: '1004', hostname: 'puppet-server', ip: '10.12.1.202', vlan_ip: ["10.10.0.4","20.20.0.4","30.30.0.4"] }
        - { vmid: '1005', hostname: 'puppet-client', ip: '10.12.1.203', vlan_ip: ["10.10.0.5","20.20.0.5","30.30.0.5"] }  
- name: Wait for prepare
  pause:
    seconds: 40
- name: Start CT
  block:
    - name: START PUPPET
      include_tasks: start_ct.yml
      loop: 
        - { vmid: '1004', hostname: 'puppet-server', ip: '10.12.1.202' }
        - { vmid: '1005', hostname: 'puppet-client', ip: '10.12.1.203' }  
