- name: Start CT
  proxmox:
    vmid: "{{ item.vmid }}"
    node: "{{ node }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    state: started
    timeout: 90

- name: Wait 60s for prepare
  pause:
    seconds: 60