#!/usr/bin/python3
import socket
import sys
import subprocess
args = eval(sys.argv[1])
hostname=socket.gethostname()
# ip=socket.gethostbyname(hostname)
if args[0]["hostname"] == hostname:
    for nic in args[0]["nic"]:
        i = 0
        state,output = subprocess.getstatusoutput("vconfig add %s %s0;ifconfig %s.%s0 %s netmask 255.255.255.0 up" % (nic, i+1, nic, i+1, args[0]["vlan_ip"][i]))
        i += 1
    print(output)